# 전처리 & 머신러닝 통합 개인과제

## Part 1. 고객 데이터 품질 개선

### 실무 시나리오

전자상거래 기업의 CRM팀은 고객별 구매 패턴을 분석하고 구매 가능성이 높은 고객을 선별하려고 합니다.  
그러나 전달받은 원본 고객 데이터에는 잘못된 자료형, 범주 표기 불일치, 결측치, 중복 데이터와 극단값이 포함되어 있어 바로 분석에 사용할 수 없습니다.

CRM팀은 **데이터 분석 담당자**로서 원본 데이터의 품질 문제를 진단하고, 이후 Part 2의 EDA와 Part 3의 구매 예측 모델링에 사용할 수 있는 분석용 데이터셋을 만들어야 합니다.

### 과제 목표

- 데이터의 구조·자료형·기초 분포를 확인하고 주요 품질 문제를 파악합니다.
- 결측치, 중복값, 이상치와 범주 표기 불일치를 분석 목적에 맞게 처리합니다.
- 조건 기반 데이터 추출과 파생변수 생성을 수행합니다.
- 전처리 결과를 검증하고 다음 Part에서 사용할 CSV 파일로 저장합니다.

### 사용 환경 및 데이터

- Python 3.X
- pandas, numpy
- `전자상거래_고객구매_원본데이터.csv`

### 제출 결과물

- Part 1 실습 노트북
- `전자상거래_고객구매_전처리완료.csv`

> 문제 1~3은 필수 문제입니다.

## 문제 1. 원본 고객 데이터 품질 진단

### 업무 상황

CRM팀에 분석 일정을 공유하기 전에 원본 데이터가 실제 분석에 사용할 수 있는 상태인지 확인해야 합니다.  
데이터를 수정하기 전에 구조와 품질 문제를 먼저 점검하고, 이후 처리해야 할 항목을 정리하세요.

### 요구사항

1. 원본 데이터를 불러오고 데이터의 크기, 컬럼, 자료형과 기초 통계량을 확인하세요.
2. 컬럼별 결측치와 전체 행 기준 중복 데이터를 확인하세요.
3. 주요 범주형 컬럼의 값을 확인하여 표기 불일치 여부를 파악하세요.
4. 이후 정제가 필요한 주요 품질 문제를 간단히 정리하세요.

### 힌트

- 데이터 구조와 기초 통계량을 함께 확인하면 자료형 오류와 비정상 범위를 찾기 쉽습니다.
- 범주형 컬럼은 고유값을 확인하여 대소문자, 공백, 한글·영문 혼용 여부를 살펴볼 수 있습니다.

In [132]:
import pandas as pd
import numpy as np
from pathlib import Path

DATA_PATH = Path("전자상거래_고객구매_데이터.csv")

# TODO: 원본 데이터를 불러와 df에 저장하세요.
df = pd.read_csv(DATA_PATH)

# TODO: 데이터의 크기, 컬럼, 자료형과 기초 통계량을 확인하세요.
# 데이터의 크기
print('데이터의 크기\n',df.shape)
print('\n데이터 컬럼\n',df.columns)
print('\n데이터 자료형')
display(df.dtypes)
print('*'*40)
print('데이터 기초 통계량\n')
display(df.describe())

# TODO: 결측치, 중복 데이터와 주요 범주형 컬럼의 값을 확인하세요.
print('컬럼별 결측치\n')
print(df.isna().sum())

print('\n중복 데이터')
print(df.duplicated().sum())

# df['SatisfactionScore']가 명목형인지 확인해 보기
print('SatisfactionScore 데이터 확인',df['SatisfactionScore'].unique())


# 주요 범주형 컬럼의 값 확인하기
import_category=['Gender','Region','MembershipLevel','CouponUsed','PreferredCategory','PurchaseStatus']
for col in import_category:
    display(df[col].value_counts(dropna=False))

데이터의 크기
 (1560, 15)

데이터 컬럼
 Index(['CustomerID', 'Gender', 'Age', 'Region', 'MembershipLevel',
       'VisitCount', 'AveragePurchaseAmount', 'TotalPurchaseAmount',
       'SatisfactionScore', 'LastPurchaseDate', 'CouponUsed',
       'PreferredCategory', 'SignupDate', 'Email', 'PurchaseStatus'],
      dtype='str')

데이터 자료형

CustomerID                   str
Gender                       str
Age                          str
Region                       str
MembershipLevel              str
VisitCount                 int64
AveragePurchaseAmount        str
TotalPurchaseAmount      float64
SatisfactionScore        float64
LastPurchaseDate             str
CouponUsed                   str
PreferredCategory            str
SignupDate                   str
Email                        str
PurchaseStatus             int64
dtype: object

****************************************
데이터 기초 통계량

        VisitCount  TotalPurchaseAmount  SatisfactionScore  PurchaseStatus
count  1560.000000         1.560000e+03        1521.000000     1560.000000
mean      9.521795         4.841402e+05           3.662853        0.485256
std       8.146008         1.410879e+06           0.759151        0.499943
min       1.000000         5.000000e+03           1.100000        0.000000
25%       7.000000         1.869500e+05           3.200000        0.000000
50%       9.000000         3.366000e+05           3.700000        0.000000
75%      11.000000         5.370750e+05           4.200000        1.000000
max     170.000000         3.000000e+07           5.000000        1.000000

컬럼별 결측치

CustomerID                0
Gender                   26
Age                      42
Region                   31
MembershipLevel          22
VisitCount                0
AveragePurchaseAmount    45
TotalPurchaseAmount       0
SatisfactionScore        39
LastPurchaseDate         30
CouponUsed                0
PreferredCategory        26
SignupDate                0
Email                     0
PurchaseStatus            0
dtype: int64

중복 데이터
60
SatisfactionScore 데이터 확인 [3.7 4.8 4.5 4.  2.6 4.1 5.  2.4 4.4 4.2 2.7 3.3 3.6 2.2 3.8 3.9 3.5 2.5
 3.4 2.9 3.1 4.7 3.2 4.3 2.8 4.9 nan 2.3 4.6 3.  1.8 2.1 1.1 1.6 2.  1.9
 1.4 1.5 1.7]

Gender
Female      713
Male        682
Other        50
NaN          26
female       19
 FEMALE      15
male         14
F            14
 MALE        14
M            13
Name: count, dtype: int64

Region
Seoul         401
Gyeonggi      362
Daejeon       172
Gwangju       155
Busan         138
Incheon       132
Daegu         114
NaN            31
 GYEONGGI      12
seoul          12
 Seoul         12
gyeonggi       11
busan           4
 Busan          4
Name: count, dtype: int64

MembershipLevel
Basic      659
Silver     413
Gold       267
VIP        115
NaN         22
 Basic      21
basic       21
silver      14
SILVER      12
gold         8
 Gold        8
Name: count, dtype: int64

CouponUsed
N      840
Y      628
No      28
 n      25
Yes     20
 y      19
Name: count, dtype: int64

PreferredCategory
Fashion          343
Electronics      257
Food             255
Beauty           237
Home             218
Sports           175
NaN               26
fashion           10
FASHION           10
electronics        8
beauty             7
 Beauty            7
 Electronics       7
Name: count, dtype: int64

PurchaseStatus
0    803
1    757
Name: count, dtype: int64

In [133]:
# AveragePurchaseAmount 값에 소수점 있는지 확인하기
pd.to_numeric(df['AveragePurchaseAmount'], errors='coerce').dropna().loc[
    lambda x: x % 1 != 0
]

# 값이 없으니까 int형으로 변환

Series([], Name: AveragePurchaseAmount, dtype: float64)

### 품질 진단 결과

- 자료형 정리가 필요한 컬럼: Age(str -> int), AveragePurchaseAmount(str -> int), LastPurchaseDate(str -> datetime), SignupDate(str->datetime)
- 표기 통일이 필요한 컬럼: Gender, Region,MembershipLevel, CouponUsed, PreferredCategory, LastPurchaseDate, SignupDate
- 결측치가 있는 컬럼:Gender, Age, Region, MembershipLevel, AveragePurchaseAmount, SatisfactionScore, LastPurchaseDate, PreferredCategory 
- 중복 데이터 확인 결과: 60개 행 중복
- 이상치 확인이 필요한 컬럼: Age, VisitCount,TotalPurchaseAmount
- 이후 처리할 주요 항목: 
1. 중복 데이터 제거
2.  범주형 컬럼 표기 통일
3.  자료형 변환
4.  결측치 처리
5.  이상치 확인 및 처리

## 문제 2. 분석 가능한 고객 데이터로 정제

### 업무 상황

품질 진단 결과를 바탕으로 고객 데이터를 분석 가능한 상태로 정리해야 합니다.  
처리 과정에서 고객의 실제 구매 행동 정보가 불필요하게 손실되지 않도록 데이터 특성을 고려하세요.

### 요구사항

1. 원본 데이터를 보존한 상태에서 정제용 데이터를 생성하세요.
2. 분석에 맞지 않는 수치형·날짜형 자료형과 범주 표기를 정리하세요.
3. 결측치와 전체 행 기준 중복 데이터를 처리하세요.
4. 주요 수치형 컬럼의 이상치를 탐지하고 적절한 방법으로 처리하세요.
5. 처리 전후의 결측치, 중복값과 이상치 상태를 확인하세요.

### 힌트

- 변환할 수 없는 문자열은 결측치로 바꾼 뒤 일관되게 처리할 수 있습니다.
- 이상치는 무조건 삭제하기보다 실제 우수 고객의 행동일 가능성도 고려하세요.
- IQR은 이상치 후보를 확인하는 대표적인 방법입니다.

In [134]:
# TODO: 원본을 보존하고 정제용 데이터 df_clean을 생성하세요.
df_clean = df.copy()

# TODO: 수치형·날짜형 자료형과 범주 표기를 정리하세요.
# 1. 수치형 자료형 변환
df_clean["Age"].value_counts(dropna=False)
df_clean["Age"] = df_clean["Age"].astype("string")
df_clean["Age"] = df_clean["Age"].str.replace("세", "", regex=False)
df_clean["Age"] = df_clean["Age"].str.replace(",", "", regex=False)
df_clean["Age"] = df_clean["Age"].str.strip()
df_clean["Age"] = pd.to_numeric(df_clean["Age"], errors="coerce")

print('최종:',df_clean["Age"].value_counts(dropna=False))
print('데이터 타입:',df_clean["Age"].dtype)

최종: Age
47     61
38     56
37     54
41     54
46     53
       ..
69      1
130     1
99      1
101     1
67      1
Name: count, Length: 63, dtype: Int64
데이터 타입: Int64

In [135]:
# 원래 값이 있었지만 숫자로 바뀌지 못한 행을 찾습니다.
original_present = df["Age"].notna()
converted_missing = df_clean["Age"].isna()
failed = original_present & converted_missing
df.loc[failed, "Age"].value_counts(dropna=False)

Age
none       1
-          1
?          1
미입력        1
thirty     1
unknown    1
Name: count, dtype: int64

In [136]:
# averagepurchaseamount
df_clean["AveragePurchaseAmount"].value_counts(dropna=False)

AveragePurchaseAmount
NaN         45
5000.0      13
143400.0     7
106100.0     6
148300.0     5
            ..
138700.0     1
172700.0     1
134600.0     1
113100.0     1
73500.0      1
Name: count, Length: 1023, dtype: int64

In [137]:
df_clean["AveragePurchaseAmount"] = df_clean["AveragePurchaseAmount"].astype("string")
df_clean["AveragePurchaseAmount"] = df_clean["AveragePurchaseAmount"].str.replace(",", "", regex=False)
df_clean["AveragePurchaseAmount"].value_counts(dropna=False)

AveragePurchaseAmount
<NA>        45
5000.0      13
143400.0     7
106100.0     6
148300.0     5
            ..
138700.0     1
172700.0     1
134600.0     1
113100.0     1
73500.0      1
Name: count, Length: 1023, dtype: Int64

In [138]:
df_clean["AveragePurchaseAmount"] = df_clean["AveragePurchaseAmount"].str.strip()
df_clean["AveragePurchaseAmount"].value_counts(dropna=False)

AveragePurchaseAmount
<NA>        45
5000.0      13
143400.0     7
106100.0     6
148300.0     5
            ..
138700.0     1
172700.0     1
134600.0     1
113100.0     1
73500.0      1
Name: count, Length: 1023, dtype: Int64

In [139]:
df_clean["AveragePurchaseAmount"] = pd.to_numeric(df_clean["AveragePurchaseAmount"], errors="coerce")
df_clean["AveragePurchaseAmount"].value_counts(dropna=False)
df_clean["AveragePurchaseAmount"].dtype

Float64Dtype()

In [140]:
# 원래 값이 있었지만 숫자로 바뀌지 못한 행을 찾습니다.
original_present = df["AveragePurchaseAmount"].notna()
converted_missing = df_clean["AveragePurchaseAmount"].isna()
failed = original_present & converted_missing
df.loc[failed, "AveragePurchaseAmount"].value_counts(dropna=False)

Series([], Name: count, dtype: int64)

In [141]:
df_clean[["Age", "AveragePurchaseAmount"]].describe()

             Age  AveragePurchaseAmount
count     1512.0                 1515.0
mean   39.666005          120540.594059
std    11.745208           52777.455516
min         18.0                 5000.0
25%         32.0                83300.0
50%         39.0               117500.0
75%         47.0               152150.0
max        130.0               292600.0

In [142]:
# 2. 날짜형 자료형 변환
 # 변환하기 전에 형태 확인하기 -> . / - 일/월/년 형식 등 (표기 형식 다양해서 통일화 먼저 필요)
for col in ['LastPurchaseDate', 'SignupDate']:
    print(f'\n===== {col} =====')

    s = df_clean[col].dropna().astype(str)

    patterns = {
        'YYYY-MM-DD': r'^\d{4}-\d{1,2}-\d{1,2}$',
        'YYYY.MM.DD': r'^\d{4}\.\d{1,2}\.\d{1,2}$',
        'YYYY/MM/DD': r'^\d{4}/\d{1,2}/\d{1,2}$',
        'DD-MM-YYYY': r'^\d{1,2}-\d{1,2}-\d{4}$',
        'DD.MM.YYYY': r'^\d{1,2}\.\d{1,2}\.\d{4}$',
        'DD/MM/YYYY': r'^\d{1,2}/\d{1,2}/\d{4}$',
    }

    for name, pattern in patterns.items():
        count = s.str.match(pattern).sum()
        print(f'{name}: {count}개')

# 날짜 컬럼
date_cols = ['LastPurchaseDate', 'SignupDate']

for col in date_cols:
    # 날짜 구분자를 '-'로 통일
    df_clean[col] = (
        df_clean[col]
        .astype('string')
        .str.replace('.', '-', regex=False)
        .str.replace('/', '-', regex=False)
    )

# LastPurchaseDate
df_clean['LastPurchaseDate'] = (
    df_clean['LastPurchaseDate']
    .astype('string')
    .str.replace('.', '-', regex=False)
    .str.replace('/', '-', regex=False)
)

df_clean['LastPurchaseDate'] = pd.to_datetime(
    df_clean['LastPurchaseDate'],
    format='%Y-%m-%d',
    errors='coerce'
)


# SignupDate
df_clean['SignupDate'] = (
    df_clean['SignupDate']
    .astype('string')
    .str.replace('.', '-', regex=False)
    .str.replace('/', '-', regex=False)
)

# DD-MM-YYYY → YYYY-MM-DD
mask = df_clean['SignupDate'].str.match(
    r'^\d{1,2}-\d{1,2}-\d{4}$',
    na=False
)

df_clean.loc[mask, 'SignupDate'] = (
    pd.to_datetime(
        df_clean.loc[mask, 'SignupDate'],
        format='%d-%m-%Y',
        errors='coerce'
    ).dt.strftime('%Y-%m-%d')
)

# 최종 날짜형 변환
df_clean['SignupDate'] = pd.to_datetime(
    df_clean['SignupDate'],
    format='%Y-%m-%d',
    errors='coerce'
)

# 자료형 잘 변환되었는지 확인하기
print(f'수치형 자료형 변환: {df_clean[['Age','AveragePurchaseAmount']].dtypes}')
print(f'날짜형 자료형 변환: {df_clean[['LastPurchaseDate', 'SignupDate']].dtypes} ')

# 3. 범주 표기 정리하기
# Gender, Region, MembershipLevel, CouponUsed, PreferredCategory
# Gender 
df_clean['Gender'] = df_clean['Gender'].str.strip().replace({
    'female':'Female',
    'FEMALE': 'Female',
    'F': 'Female',
    'male': 'Male',
    'MALE': 'Male',
    'M': 'Male',

})

# Region - unique 찍어본 결과 대소문자, 띄어쓰기 문제
df_clean['Region'] = df_clean['Region'].str.strip().str.title()

#MembershipLevel
df_clean['MembershipLevel'] = (
    df_clean['MembershipLevel']
    .str.strip()
    .str.title()
    .replace({'Vip': 'VIP'})
)

# CouponUsed
df_clean['CouponUsed'] = df_clean['CouponUsed'].str.strip().replace({
    'No': 'N',
    'n': 'N',
    'Yes': 'Y',
    'y': 'Y'
})

#PreferredCategory
df_clean['PreferredCategory'] = (
    df_clean['PreferredCategory']
    .str.strip()
    .str.title()
)

# 범주형 데이터 제대로 통일되었는지 확인해 보기
for col in ['Gender', 'Region', 'MembershipLevel',
            'CouponUsed', 'PreferredCategory']:
    print(f'\n[{col}]')
    display(df_clean[col].value_counts(dropna=False))

===== LastPurchaseDate =====
YYYY-MM-DD: 1495개
YYYY.MM.DD: 15개
YYYY/MM/DD: 20개
DD-MM-YYYY: 0개
DD.MM.YYYY: 0개
DD/MM/YYYY: 0개

===== SignupDate =====
YYYY-MM-DD: 1545개
YYYY.MM.DD: 0개
YYYY/MM/DD: 0개
DD-MM-YYYY: 15개
DD.MM.YYYY: 0개
DD/MM/YYYY: 0개
수치형 자료형 변환: Age                        Int64
AveragePurchaseAmount    Float64
dtype: object
날짜형 자료형 변환: LastPurchaseDate    datetime64[us]
SignupDate          datetime64[us]
dtype: object

[Gender]

Gender
Female    761
Male      723
Other      50
NaN        26
Name: count, dtype: int64

[Region]

Region
Seoul       425
Gyeonggi    385
Daejeon     172
Gwangju     155
Busan       146
Incheon     132
Daegu       114
NaN          31
Name: count, dtype: int64

[MembershipLevel]

MembershipLevel
Basic     701
Silver    439
Gold      283
VIP       115
NaN        22
Name: count, dtype: int64

[CouponUsed]

CouponUsed
N    893
Y    667
Name: count, dtype: int64

[PreferredCategory]

PreferredCategory
Fashion        363
Electronics    272
Food           255
Beauty         251
Home           218
Sports         175
NaN             26
Name: count, dtype: int64

In [143]:
# TODO: 결측치와 전체 행 기준 중복 데이터를 처리하세요.
 # 1. 전체 칼럼의 값이 완전히 동일한 중복 행인지 확인하기
duplicated_df = df_clean[df_clean.duplicated(keep=False)]
duplicated_df = duplicated_df.sort_values(by='CustomerID', ascending=False)
display(duplicated_df)

# 1.2 실제로  완전히 중복된 값이란거 확인 -> 중복 데이터 첫번째 등장한 행만 유지
df_clean = df_clean.drop_duplicates(keep='first')

# 1.3 잘 삭제되었는지 확인
print('중복 데이터 삭제 후: ',df_clean.duplicated().sum())

df_clean['Age'] = df_clean['Age'].astype(float)
df_clean['AveragePurchaseAmount'] = df_clean['AveragePurchaseAmount'].astype(float)


# 2. 결측치 처리하기
# 결측치가 있는 행:   Gender, Age, Region, MembershipLevel, AveragePurchaseAmount, SatisfactionScore, LastPurchaseDate, PreferredCategory 
# 2.1 이상치가 있을 가능성이 있는 수치형 변수 - 중앙값으로 대체하기
#  - 이상치 확인이 필요한 컬럼: Age, VisitCount,AveragePurchaseAmount, TotalPurchaseAmount
#  - membershiplevel, PreferredCategory로 유의미한 차이가 있는지 확인하기
print('membership,category 선호도별로 결측치 대체할 만한 유의미한 차이가 있는지 확인')
display(df_clean.groupby(
    ['MembershipLevel', 'PreferredCategory']
)[
    ['VisitCount','AveragePurchaseAmount', 'TotalPurchaseAmount', 'Age']
].agg(['count', 'mean', 'median']))

# 2.1.1 MembershipLevel + PreferredCategory별 중앙값으로 결측치 대체
group_cols = ['MembershipLevel', 'PreferredCategory']

for col in [
    'VisitCount',
    'AveragePurchaseAmount',
    'TotalPurchaseAmount',
    'Age'
]:
    df_clean[col] = df_clean[col].fillna(
        df_clean.groupby(group_cols)[col].transform('median')
    )

# 2.1.2. 위 그룹 기준으로도 채워지지 않은 결측치는 전체 중앙값으로 대체
for col in [
    'VisitCount',
    'AveragePurchaseAmount',
    'TotalPurchaseAmount',
    'Age'
]:
    df_clean[col] = df_clean[col].fillna(
        df_clean[col].median()
    )


# 2.2 이상치 확률이 적은 수치형 변수 - 평균으로 대체하기
# - satisfactionscore
df_clean['SatisfactionScore'] = df_clean['SatisfactionScore'].fillna(
    df_clean['SatisfactionScore'].mean()
)

# 2.3 범주형 변수: 'Gender', 'Region', 'MembershipLevel','CouponUsed', 'PreferredCategory'
 # 최빈값으로 대체하기
 # or NaN 값을 Unknown으로 처리하기 (결측 자체가 하나의 정보일 수 있다는 의미) 
 # -> 'Gender'나 'Region', 'CouponUsed','PreferredCategory' 최빈값을 대체하는 거 의미 없음 -> Unknow 값으로 처리하기
categorical_cols = [
    'Gender',
    'Region',
    'CouponUsed',
    'PreferredCategory'
]

for col in categorical_cols:
    df_clean[col] = df_clean[col].fillna('Unknown')

# membershiplevel은 TotalPurchaseAmount랑 비교해서 유의미한 값인지 확인 후 -> 대체
display(df_clean.groupby('MembershipLevel')[
    ['TotalPurchaseAmount']
].agg(['count', 'mean', 'median'])
)

# 1. MembershipLevel별 TotalPurchaseAmount의 중앙값 계산
membership_median = df_clean.groupby('MembershipLevel')[
    'TotalPurchaseAmount'
].median()

#2. 등급 순서대로 정렬
membership_median = membership_median.reindex(
    ['Basic', 'Silver', 'Gold', 'VIP']
)

print(membership_median)

#3. 등급 사이의 구간 경계값 자동 계산
thresholds = [
    (membership_median.iloc[i] + membership_median.iloc[i + 1]) / 2
    for i in range(len(membership_median) - 1)
]

print(thresholds)

#4. 계산된 구간 이용해서 결측치 대체하기
def fill_membership_level(row):
    if pd.notna(row['MembershipLevel']):
        return row['MembershipLevel']

    amount = row['TotalPurchaseAmount']

    if amount < thresholds[0]:
        return 'Basic'
    elif amount < thresholds[1]:
        return 'Silver'
    elif amount < thresholds[2]:
        return 'Gold'
    else:
        return 'VIP'


df_clean['MembershipLevel'] = df_clean.apply(
    fill_membership_level,
    axis=1
)

# 날짜형 결측치 삭제
df_clean = df_clean.dropna(subset=['LastPurchaseDate'])



# TODO: 처리 전후 결과를 확인하세요.
# 컬럼별 결측치 개수 확인
print('\n전체 결측치 개수:', df_clean.isna().sum().sum())

,CustomerID,Gender,Age,Region,MembershipLevel,VisitCount,AveragePurchaseAmount,TotalPurchaseAmount,SatisfactionScore,LastPurchaseDate,CouponUsed,PreferredCategory,SignupDate,Email,PurchaseStatus
1324,CUST101488,Female,35,Gwangju,Gold,6,91000.0,83100.0,2.3,2026-05-30,Y,Home,2023-10-22,customer1488@example.com,0
1397,CUST101488,Female,35,Gwangju,Gold,6,91000.0,83100.0,2.3,2026-05-30,Y,Home,2023-10-22,customer1488@example.com,0
1489,CUST101437,Male,53,Daejeon,Basic,9,94900.0,384200.0,4.1,2026-05-25,N,Fashion,2022-12-23,customer1437@example.com,0
233,CUST101437,Male,53,Daejeon,Basic,9,94900.0,384200.0,4.1,2026-05-25,N,Fashion,2022-12-23,customer1437@example.com,0
964,CUST101420,Female,33,Gyeonggi,Silver,6,166700.0,315500.0,2.8,2026-05-22,N,Beauty,2023-05-10,customer1420@example.com,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
616,CUST100030,Female,50,Daejeon,Silver,9,112000.0,429200.0,3.6,2026-05-08,Y,Beauty,2024-06-18,customer30@example.com,0
1258,CUST100021,Other,25,Daejeon,Basic,11,83400.0,213200.0,4.3,2026-01-04,N,Beauty,2021-09-30,customer21@example.com,0
256,CUST100021,Other,25,Daejeon,Basic,11,83400.0,213200.0,4.3,2026-01-04,N,Beauty,2021-09-30,customer21@example.com,0
105,CUST100014,Male,50,Daegu,Silver,12,162300.0,21000000.0,4.1,2026-03-06,Y,Electronics,2025-12-21,customer14@example.com,1
867,CUST100014,Male,50,Daegu,Silver,12,162300.0,21000000.0,4.1,2026-03-06,Y,Electronics,2025-12-21,customer14@example.com,1

중복 데이터 삭제 후:  0
membership,category 선호도별로 결측치 대체할 만한 유의미한 차이가 있는지 확인

                                  VisitCount                    \
                                       count       mean median
MembershipLevel PreferredCategory
Basic           Beauty                   107  10.205607    9.0
                Electronics              132   9.340909    9.0
                Fashion                  144   9.097222    9.0
                Food                     113   8.902655    9.0
                Home                      86  10.139535    8.0
                Sports                    84   9.488095   10.0
Gold            Beauty                    52   8.711538    9.0
                Electronics               37  11.891892   10.0
                Fashion                   67   9.432836    9.0
                Food                      44   8.340909    8.0
                Home                      44   8.522727    9.0
                Sports                    29   9.103448   10.0
Silver          Beauty                    63   8.857143    9.0
                Electronics               76   9.118421    9.0
                Fashion                  112  10.455357    9.0
                Food                      65   8.815385    9.0
                Home                      59   9.000000    9.0
                Sports                    32   9.875000   10.0
VIP             Beauty                    13  10.461538   10.0
                Electronics               16   8.312500    8.5
                Fashion                   21   9.714286   10.0
                Food                      21   9.285714    9.0
                Home                      17   7.705882    8.0
                Sports                    18   8.277778    8.0

                                  AveragePurchaseAmount                 \
                                                  count           mean
MembershipLevel PreferredCategory
Basic           Beauty                              103   98049.514563
                Electronics                         129  144032.558140
                Fashion                             140   83326.428571
                Food                                106   84418.867925
                Home                                 86   74502.325581
                Sports                               83   81383.132530
Gold            Beauty                               47  149482.978723
                Electronics                          35  209120.000000
                Fashion                              64  137415.625000
                Food                                 43  138374.418605
                Home                                 43  146146.511628
                Sports                               29  138596.551724
Silver          Beauty                               62  120122.580645
                Electronics                          74  169606.756757
                Fashion                             110  101874.545455
                Food                                 64   98896.875000
                Home                                 56  104975.000000
                Sports                               32  124356.250000
VIP             Beauty                               13  205669.230769
                Electronics                          15  248413.333333
                Fashion                              21  187123.809524
                Food                                 21  189552.380952
                Home                                 17  185647.058824
                Sports                               17  184370.588235

                                            TotalPurchaseAmount                \
                                     median               count          mean
MembershipLevel PreferredCategory
Basic           Beauty              99600.0                 107  5.158112e+05
                Electronics        143800.0                 132  5.351394e+05
                Fashion             81950.0                 144  2.953021e+05
                Food                84000.0                 113  2.820584e+05
                Home                74750.0                  86  2.423581e+05
                Sports              83100.0                  84  2.608893e+05
Gold            Beauty             144000.0                  52  4.709885e+05
                Electronics        206600.0                  37  1.052324e+06
                Fashion            138500.0                  67  9.172104e+05
                Food               135900.0                  44  3.960318e+05
                Home               152600.0                  44  4.387364e+05
                Sports             139600.0                  29  4.396448e+05
Silver          Beauty             121600.0                  63  4.025349e+05
                Electronics        166850.0                  76  8.217487e+05
                Fashion            101300.0                 112  3.317420e+05
                Food                95350.0                  65  3.214185e+05
                Home               107500.0                  59  3.417203e+05
                Sports             120750.0                  32  1.197747e+06
VIP             Beauty             200200.0                  13  9.039000e+05
                Electronics        251600.0                  16  7.711750e+05
                Fashion            180600.0                  21  6.501857e+05
                Food               198300.0                  21  6.332381e+05
                Home               190700.0                  17  5.415294e+05
                Sports             177900.0                  18  4.684000e+05

                                              Age
                                     median count       mean median
MembershipLevel PreferredCategory
Basic           Beauty             306800.0   103  39.543689   38.0
                Electronics        404800.0   127  40.685039   42.0
                Fashion            226750.0   142  39.683099   41.0
                Food               242900.0   105  39.238095   38.0
                Home               198650.0    85  39.435294   39.0
                Sports             244200.0    80  38.650000   37.0
Gold            Beauty             424900.0    52  40.250000   41.0
                Electronics        595200.0    36  39.194444   38.0
                Fashion            399500.0    64  38.984375   37.5
                Food               345050.0    44  39.954545   38.5
                Home               353650.0    44  38.363636   39.0
                Sports             360100.0    29  37.827586   36.0
Silver          Beauty             358000.0    62  40.483871   37.5
                Electronics        509200.0    73  38.287671   39.0
                Fashion            262450.0   109  40.302752   39.0
                Food               267300.0    64  40.203125   40.0
                Home               336700.0    55  40.763636   42.0
                Sports             363100.0    32  41.781250   41.5
VIP             Beauty             911500.0    13  42.076923   42.0
                Electronics        691750.0    16  38.125000   38.0
                Fashion            598800.0    20  40.350000   40.5
                Food               597100.0    20  35.150000   34.0
                Home               561700.0    16  45.437500   42.5
                Sports             457350.0    17  34.941176   35.0

                TotalPurchaseAmount
                              count           mean    median
MembershipLevel
Basic                           675  363237.185185  259800.0
Gold                            276  635726.811594  402300.0
Silver                          419  501095.704057  347400.0
VIP                             108  646874.074074  593300.0

MembershipLevel
Basic     259800.0
Silver    347400.0
Gold      402300.0
VIP       593300.0
Name: TotalPurchaseAmount, dtype: float64
[np.float64(303600.0), np.float64(374850.0), np.float64(497800.0)]

전체 결측치 개수: 0

In [129]:
# TODO: Q1, Q3, IQR, 하한과 상한을 반환하세요.
def detect_outliers_iqr(df, col, id_col="CustomerID", show=5):
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    outliers = (df[col] < lower) | (df[col] > upper)
    count = outliers.sum()

    print(f"--- {col} ---")
    print(f"Q1: {q1}, Q3: {q3}, IQR: {iqr}")
    print(f"하한: {lower}, 상한: {upper}")
    print(f"이상치 후보 수: {count}")

    result = df.loc[outliers, [id_col, col]]
    display(result.head(show))  # 노트북이면 display, 아니면 print(result.head(show))

    return {
        "col": col,
        "q1": q1,
        "q3": q3,
        "iqr": iqr,
        "lower": lower,
        "upper": upper,
        "outlier_mask": outliers,
        "outlier_count": count
    }

In [144]:
cols_to_check = [
    "Age",
    "VisitCount",
    "AveragePurchaseAmount",
    "TotalPurchaseAmount",
    "SatisfactionScore"
]

results = {}

for col in cols_to_check:
    results[col] = detect_outliers_iqr(df_clean, col)

--- Age ---
Q1: 32.0, Q3: 47.0, IQR: 15.0
하한: 9.5, 상한: 69.5
이상치 후보 수: 11

     CustomerID    Age
2    CUST100168  105.0
537  CUST100069   72.0
568  CUST100234   79.0
585  CUST100496  120.0
604  CUST101281   76.0

--- VisitCount ---
Q1: 7.0, Q3: 11.0, IQR: 4.0
하한: 1.0, 상한: 17.0
이상치 후보 수: 15

     CustomerID  VisitCount
102  CUST100455         170
188  CUST100565          21
281  CUST101188          19
312  CUST100672         150
394  CUST101168          19

--- AveragePurchaseAmount ---
Q1: 83250.0, Q3: 150875.0, IQR: 67625.0
하한: -18187.5, 상한: 252312.5
이상치 후보 수: 17

     CustomerID  AveragePurchaseAmount
6    CUST100600               272600.0
53   CUST100848               280400.0
110  CUST101043               255100.0
167  CUST100068               258300.0
267  CUST100347               277700.0

--- TotalPurchaseAmount ---
Q1: 184675.0, Q3: 535275.0, IQR: 350600.0
하한: -341225.0, 상한: 1061175.0
이상치 후보 수: 51

    CustomerID  TotalPurchaseAmount
6   CUST100600            1164900.0
45  CUST100978            1120600.0
51  CUST101370            1456300.0
53  CUST100848            1593800.0
75  CUST100891           18000000.0

--- SatisfactionScore ---
Q1: 3.2, Q3: 4.2, IQR: 1.0
하한: 1.7000000000000002, 상한: 5.7
이상치 후보 수: 10

     CustomerID  SatisfactionScore
175  CUST101157                1.1
199  CUST101006                1.6
241  CUST101289                1.6
290  CUST101323                1.6
782  CUST100105                1.4

In [145]:
# 경계값 조정하기
def clip_outliers(df_before, df_after, col, lower, upper, show=5):
    # float64로 변환 후 클리핑
    df_after[col] = df_after[col].astype("float64")
    df_after[col] = df_after[col].clip(lower=lower, upper=upper)

    # 변경된 값 비교
    changed = df_before[col] != df_after[col]
    print(f"--- {col} ---")
    print("변경한 값 수:", changed.sum())

    comparison = pd.DataFrame()
    comparison["처리 전"] = df_before.loc[changed, col]
    comparison["처리 후"] = df_after.loc[changed, col]
    display(comparison.head(show))

    print(f"{col} value_counts:")
    display(df_after[col].value_counts(dropna=False))
    print()

    return changed

In [146]:
df_before_outlier = df_clean.copy()

cols_to_check = ["Age", "VisitCount", "AveragePurchaseAmount", "TotalPurchaseAmount", "SatisfactionScore"]

changed_masks = {}
for col in cols_to_check:
    lower = results[col]["lower"]
    upper = results[col]["upper"]
    changed_masks[col] = clip_outliers(df_before_outlier, df_clean, col, lower, upper)

--- Age ---
변경한 값 수: 11

      처리 전  처리 후
2    105.0  69.5
537   72.0  69.5
568   79.0  69.5
585  120.0  69.5
604   76.0  69.5

Age value_counts:

Age
38.0    68
47.0    59
37.0    57
41.0    55
42.0    53
35.0    52
46.0    51
32.0    50
36.0    49
39.0    48
44.0    48
43.0    47
40.0    44
31.0    44
33.0    43
18.0    41
34.0    39
45.0    38
49.0    38
48.0    37
29.0    35
30.0    33
50.0    30
25.0    30
26.0    27
53.0    26
27.0    26
28.0    24
57.0    22
54.0    21
51.0    21
23.0    20
52.0    20
21.0    18
24.0    16
56.0    14
55.0    14
22.0    12
60.0    12
69.5    11
19.0    11
58.0    10
59.0    10
20.0     9
63.0     7
61.0     7
62.0     4
37.5     4
65.0     4
66.0     3
64.0     2
68.0     2
40.5     1
69.0     1
42.5     1
67.0     1
Name: count, dtype: int64

--- VisitCount ---
변경한 값 수: 15

     처리 전  처리 후
102   170  17.0
188    21  17.0
281    19  17.0
312   150  17.0
394    19  17.0

VisitCount value_counts:

VisitCount
9.0     197
8.0     189
7.0     180
10.0    180
11.0    146
6.0     135
12.0    107
5.0      84
13.0     67
4.0      47
14.0     46
15.0     28
3.0      22
17.0     22
16.0     15
2.0       4
1.0       1
Name: count, dtype: int64

--- AveragePurchaseAmount ---
변경한 값 수: 17

         처리 전      처리 후
6    272600.0  252312.5
53   280400.0  252312.5
110  255100.0  252312.5
167  258300.0  252312.5
267  277700.0  252312.5

AveragePurchaseAmount value_counts:

AveragePurchaseAmount
252312.5    17
5000.0      13
84000.0      9
99600.0      8
144000.0     7
            ..
199200.0     1
138700.0     1
172700.0     1
134600.0     1
113100.0     1
Name: count, Length: 984, dtype: int64

--- TotalPurchaseAmount ---
변경한 값 수: 51

          처리 전       처리 후
6    1164900.0  1061175.0
45   1120600.0  1061175.0
51   1456300.0  1061175.0
53   1593800.0  1061175.0
75  18000000.0  1061175.0

TotalPurchaseAmount value_counts:

TotalPurchaseAmount
1061175.0    51
408100.0      3
97400.0       3
283000.0      3
227000.0      3
             ..
59700.0       1
417000.0      1
799600.0      1
92800.0       1
486200.0      1
Name: count, Length: 1299, dtype: int64

--- SatisfactionScore ---
변경한 값 수: 10

     처리 전  처리 후
175   1.1   1.7
199   1.6   1.7
241   1.6   1.7
290   1.6   1.7
782   1.4   1.7

SatisfactionScore value_counts:

SatisfactionScore
3.60000    78
3.90000    75
3.30000    74
3.80000    70
4.20000    68
3.70000    67
3.50000    66
3.20000    63
4.10000    61
3.40000    61
5.00000    58
4.00000    57
3.00000    56
3.10000    55
4.40000    51
4.50000    47
4.30000    47
4.70000    38
4.60000    36
2.80000    35
3.66015    35
2.70000    34
2.60000    33
2.90000    32
4.90000    32
4.80000    25
2.40000    25
2.30000    19
2.50000    18
2.20000    14
2.10000    11
1.70000    10
2.00000    10
1.80000     6
1.90000     3
Name: count, dtype: int64

In [147]:
# TODO: 처리 전후 이상치 상태를 확인하세요
quality_report = pd.DataFrame()
quality_report["원본 결측 수"] = df.isna().sum()
quality_report["정제 후 결측 수"] = df_clean.isna().sum()
quality_report

                       원본 결측 수  정제 후 결측 수
CustomerID                   0          0
Gender                      26          0
Age                         42          0
Region                      31          0
MembershipLevel             22          0
VisitCount                   0          0
AveragePurchaseAmount       45          0
TotalPurchaseAmount          0          0
SatisfactionScore           39          0
LastPurchaseDate            30          0
CouponUsed                   0          0
PreferredCategory           26          0
SignupDate                   0          0
Email                        0          0
PurchaseStatus               0          0

In [148]:
print("행 수:", len(df), "→", len(df_clean))
print("전체 행 중복:", df.duplicated().sum(), "→", df_clean.duplicated().sum())

행 수: 1560 → 1470
전체 행 중복: 60 → 0

In [149]:
# iqr 처리후
def compare_outlier_count(df_clean, col, before_count):
    q1 = df_clean[col].quantile(0.25)
    q3 = df_clean[col].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    outliers = (df_clean[col] < lower) | (df_clean[col] > upper)
    after_count = outliers.sum()

    print(f"--- {col} ---")
    print("처리 전 후보 수:", before_count)
    print("처리 후 후보 수:", after_count)
    print()

    return {
        "col": col,
        "q1": q1,
        "q3": q3,
        "iqr": iqr,
        "lower": lower,
        "upper": upper,
        "before_count": before_count,
        "after_count": after_count
    }

In [150]:
cols_to_check = ["Age", "VisitCount", "AveragePurchaseAmount", "TotalPurchaseAmount", "SatisfactionScore"]

after_results = {}
for col in cols_to_check:
    before_count = results[col]["outlier_count"]
    after_results[col] = compare_outlier_count(df_clean, col, before_count)

--- Age ---
처리 전 후보 수: 11
처리 후 후보 수: 0

--- VisitCount ---
처리 전 후보 수: 15
처리 후 후보 수: 0

--- AveragePurchaseAmount ---
처리 전 후보 수: 17
처리 후 후보 수: 0

--- TotalPurchaseAmount ---
처리 전 후보 수: 51
처리 후 후보 수: 0

--- SatisfactionScore ---
처리 전 후보 수: 10
처리 후 후보 수: 0

## 문제 3. 분석용 변수 생성 및 다음 단계 데이터 준비

### 업무 상황

정제된 데이터를 CRM팀의 고객군 분석과 구매 예측 업무에 활용하려면, 원본 컬럼만으로 확인하기 어려운 고객 특성을 분석용 변수로 표현해야 합니다.  
필요한 고객을 조건에 따라 추출하고, 이후 Part 2와 Part 3에서 활용할 파생변수를 만든 뒤 최종 데이터를 저장하세요.

### 요구사항

1. 정제된 데이터에서 업무적으로 의미 있는 조건을 설정하여 고객 데이터를 추출하세요.
2. 고객 분석에 활용할 파생변수를 **2개 이상** 생성하세요.
3. 생성한 파생변수의 값과 분포가 적절한지 확인하세요.
4. 최종 데이터의 결측치, 중복값, 고객 식별자와 타깃 값을 검증하세요.
5. 전처리 완료 데이터를 `전자상거래_고객구매_전처리완료.csv`로 저장하세요.

### 힌트

- 연령대, 구매 수준, 최근 구매 여부, 우수 고객 여부 등을 파생변수 후보로 고려할 수 있습니다.
- 조건 추출 결과는 별도 DataFrame으로 확인해도 되며, 최종 데이터 전체를 삭제할 필요는 없습니다.

- 고객 연령을 구간화한 `AgeGroup`을 생성하세요.
- 총구매금액을 기준으로 `PurchaseGrade`를 생성하세요.

In [151]:
visit_median = df_clean["VisitCount"].median()
visit_median

np.float64(9.0)

In [152]:
visit_condition = df_clean["VisitCount"] >= visit_median
purchase_condition = df_clean["TotalPurchaseAmount"] > 0
selected_customers = df_clean[visit_condition & purchase_condition]
selected_customers = selected_customers.copy()

In [153]:
print("조건에 맞는 고객 수:", len(selected_customers))
selected_customers.head()

조건에 맞는 고객 수: 808

,CustomerID,Gender,Age,Region,MembershipLevel,VisitCount,AveragePurchaseAmount,TotalPurchaseAmount,SatisfactionScore,LastPurchaseDate,CouponUsed,PreferredCategory,SignupDate,Email,PurchaseStatus
2,CUST100168,Male,69.5,Gwangju,Silver,12.0,185800.0,1055800.0,4.5,2026-06-06,N,Beauty,2022-02-15,customer168@example.com,1
4,CUST100312,Male,37.0,Gyeonggi,Basic,14.0,123700.0,576000.0,4.0,2026-04-16,N,Home,2025-11-08,customer312@example.com,1
6,CUST100600,Female,47.0,Daejeon,VIP,10.0,252312.5,1061175.0,2.6,2026-01-31,Y,Beauty,2025-01-28,customer600@example.com,1
10,CUST100037,Female,53.0,Gyeonggi,Basic,10.0,153900.0,629800.0,4.4,2026-02-18,N,Electronics,2024-09-05,customer37@example.com,1
11,CUST101156,Male,23.0,Gyeonggi,Basic,12.0,67700.0,451500.0,4.2,2026-03-31,Y,Home,2022-06-12,customer1156@example.com,1

In [154]:
# AgeGroup 생성
age_bins = [0, 29, 39, 49, 59, float("inf")]
age_labels = ["20대 이하", "30대", "40대", "50대", "60대 이상"]

df_clean["AgeGroup"] = pd.cut(
    df_clean["Age"],
    bins=age_bins,
    labels=age_labels,
    include_lowest=True
)


display(df_clean[["Age", "AgeGroup"]].head(10))

     Age AgeGroup
0   40.0      40대
1   39.0      30대
2   69.5   60대 이상
3   44.0      40대
4   37.0      30대
6   47.0      40대
7   26.0   20대 이하
8   56.0      50대
9   42.0      40대
10  53.0      50대

In [157]:
purchase_q1 = df_clean["TotalPurchaseAmount"].quantile(0.25)
purchase_q3 = df_clean["TotalPurchaseAmount"].quantile(0.75)
print("Q1:", purchase_q1)
print("Q3:", purchase_q3)

Q1: 184675.0
Q3: 535275.0

In [ ]:
df_clean["PurchaseGrade"] = "Medium"

In [159]:
df_clean["PurchaseGrade"].value_counts(dropna=False)

PurchaseGrade
Medium    1470
Name: count, dtype: int64

In [160]:
low_condition = df_clean["TotalPurchaseAmount"] <= purchase_q1
df_clean.loc[low_condition, "PurchaseGrade"] = "Low"

In [161]:
df_clean["PurchaseGrade"].value_counts(dropna=False)

PurchaseGrade
Medium    1102
Low        368
Name: count, dtype: int64

In [162]:
high_condition = df_clean["TotalPurchaseAmount"] > purchase_q3
df_clean.loc[high_condition, "PurchaseGrade"] = "High"

In [163]:
df_clean["PurchaseGrade"].value_counts(dropna=False)

PurchaseGrade
Medium    734
Low       368
High      368
Name: count, dtype: int64

In [164]:
df_clean[["TotalPurchaseAmount", "PurchaseGrade"]].head(10)

    TotalPurchaseAmount PurchaseGrade
0              139800.0           Low
1              159200.0           Low
2             1055800.0          High
3              413200.0        Medium
4              576000.0          High
6             1061175.0          High
7               40700.0           Low
8              443500.0        Medium
9               70700.0           Low
10             629800.0          High

In [165]:
df_clean["AgeGroup"].value_counts(dropna=False)

AgeGroup
30대       487
40대       472
20대 이하    269
50대       188
60대 이상     54
Name: count, dtype: int64

In [166]:
df_clean["AgeGroup"].isna().sum()

np.int64(0)

In [167]:
df_clean["PurchaseGrade"].value_counts(dropna=False)

PurchaseGrade
Medium    734
Low       368
High      368
Name: count, dtype: int64

In [168]:
df_clean["PurchaseGrade"].isna().sum()

np.int64(0)

# 문제 4. 데이터 정제 및 파생변수 설계 근거 설명

## 업무 상황

CRM팀은 전처리 결과가 단순히 실행되는 것뿐 아니라,
적용한 처리 기준과 파생변수가 실제 분석 목적에 적합한지 확인하려고 합니다.

문제 1~3에서 수행한 결과를 바탕으로 다음 내용을 설명하세요.

## 요구사항

### 4-1. 데이터 품질 문제의 영향과 한계

1. 문제 1에서 확인한 주요 품질 문제를 한 가지 이상 선택하세요.
2. 해당 문제가 이후 EDA 또는 모델링 결과에 미칠 수 있는 영향을 설명하세요.
3. 현재 데이터만으로 판단하기 어려운 점이나 추가 확인이 필요한 조건을 작성하세요.

### 4-2. 결측치·이상치 처리 방법의 선택 근거

1. 적용한 결측치 처리 방법을 한 가지 이상 제시하세요.
2. 해당 방법을 선택한 이유를 데이터 특성과 연결하여 작성하세요.
3. 적용한 이상치 처리 방법과 처리 시 주의할 점을 설명하세요.

### 4-3. 파생변수의 활용 의도와 한계

1. `파생변수1`과 `파생변수2`의 생성 기준을 설명하세요.
2. 각 파생변수가 Part 2 고객 특성 분석에서 어떻게 활용될 수 있는지 작성하세요.
3. 파생변수 사용 시 발생할 수 있는 정보 손실 또는 해석상의 한계를 설명하세요.

## 문제 4 결과 작성

### 4-1. 데이터 품질 문제의 영향과 한계

- 선택한 품질 문제:
- EDA 또는 모델링에 미치는 영향:
- 추가 확인이 필요한 조건 또는 한계:

### 4-2. 결측치·이상치 처리 방법의 선택 근거

- 결측치 처리 방법:
- 해당 방법을 선택한 이유:
- 이상치 처리 방법:
- 이상치 처리 시 주의점:

### 4-3. 파생변수의 활용 의도와 한계

- `AgeGroup` 생성 기준과 활용 목적:
- `PurchaseGrade` 생성 기준과 활용 목적:
- 파생변수 사용 시 한계: